import { Header } from "@/Components";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "GetSleep",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`${inter.className} `}>
        <Header />
        <div className=''>{children}</div>
      </body>
    </html>
  );
}
